# Generated by Django 5.1.2 on 2024-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALAXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela')], default='', max_length=100),
        ),
    ]
